[[main]]
none = "none"

[[main]]
name = "About Me"
pageRef = "about/index"
identifier = "EaIMiOGcgY"
weight = 9_999

[[main]]
name = "All Posts"
pageRef = "blog"
weight = 9_999


[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10
