colorScheme = "isiturner"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableA11y = false
enableSearch = true
enableCodeCopy = false
enableStructuredBreadcrumbs = false
replyByEmail = false
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
hotlinkFeatureImage = false
fingerprintAlgorithm = "sha512"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"
firebase = { }
fathomAnalytics = { }
umamiAnalytics = { }
selineAnalytics = { }
buymeacoffee = { }
verification = { }
rssnext = { }
advertisement = { }
defaultFeaturedImage = "background.png"

[header]
layout = "fixed-fill"

[footer]
showMenu = true
showCopyright = false
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "custom"
showRecent = true
showRecentItems = 6
showMoreLink = false
showMoreLinkDest = "/blog/"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true
disableHeroImageFilter = false
homepageImage = "background.png"

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = false
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showCategoryOnly = false
showAuthorsBadges = false
showWordCount = true
showZenMode = false
heroStyle = "background"
showRelatedContent = true
relatedContentLimit = "3"

[list]
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = false
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = true

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false
